version: '3'

services:
  app:
    build: .
    container_name: app
    env_file:
      - ./src/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./src:/app

  db:
      image: postgres:13.5
      container_name: virtual_shopping_db
      environment:
        POSTGRES_PASSWORD: admin
        POSTGRES_USER: admin
        POSTGRES_DB: virtual_shopping
      ports:
        - "5432:5432"
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data/
        - ./sql:/docker-entrypoint-initdb.d
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
        interval: 10s
        timeout: 5s
        retries: 3
      logging:
        driver: json-file
        options:
          max-size: "50m"
          max-file: "10"
    
volumes:
  postgres_data: